version: "3.8"
services:
  mysql:
    image: todo-db:1.0   # 없으면 mysql:8.0 써도 됨
    container_name: todo-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: todo
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

